esphome:
  name: kiyari
  friendly_name: KIYARI
  on_boot:
    priority: -100
    then:
      - delay: 2s
      - media_player.play_media:
          id: kiyari_player
          media_url: "http://10.103.253.164:8000/hello.wav"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

logger:

api:

ota:
  - platform: esphome

wifi:
  ssid: "Lucifer"
  password: "12345678"

  ap:
    ssid: "Lucifer"
    password: "12345678"

captive_portal:

psram:
  mode: octal

web_server:
  port: 80

button:
  - platform: restart
    name: "Device Restart"
  - platform: template
    name: "Play Hello"
    id: play_hello_btn
    on_press:
      then:
        - media_player.play_media:
            id: kiyari_player
            media_url: "http://10.103.253.164:8000/hello.wav"
  - platform: template
    name: "Play Beep"
    id: play_beep_btn
    on_press:
      then:
        - media_player.play_media:
            id: kiyari_player
            media_url: "http://10.103.253.164:8000/beep.wav"

i2s_audio:
  - id: i2s_out
    i2s_lrclk_pin: GPIO16
    i2s_bclk_pin: GPIO15

speaker:
  - platform: i2s_audio
    id: kiyari_speaker
    i2s_audio_id: i2s_out
    i2s_dout_pin: GPIO7
    dac_type: external
    sample_rate: 16000

media_player:
  - platform: speaker
    id: kiyari_player
    name: "KIYARI Speaker"
    announcement_pipeline:
      speaker: kiyari_speaker
    buffer_size: 100000